"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Lutometry.py']
DATA_FILES = [('', ['images'])]
OPTIONS = {
    'iconfile' : 'images/LUTometryIcon.icns',
    'packages': ['numpy', 'matplotlib', 'progress', 'kdtree', 'PyQt5'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)